/** @type {import('tailwindcss').Config} */
// Design tokens extracted verbatim from the 20 Google Stitch screens for CampusFit.
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary': '#ffffff',
        tertiary: '#7e3cbb',
        'surface-variant': '#e0e3df',
        'secondary-container': '#feae2c',
        'secondary-fixed': '#ffddb4',
        'primary-fixed': '#64fdb7',
        'primary-container': '#1ecc8b',
        'surface-container': '#ecefeb',
        'surface-container-low': '#f1f4f0',
        'on-secondary-fixed-variant': '#633f00',
        'on-tertiary-fixed-variant': '#641ea1',
        'surface': '#f7faf6',
        'primary': '#006c47',
        'inverse-surface': '#2d312f',
        'on-tertiary-fixed': '#2c0050',
        'on-background': '#181c1a',
        'error-container': '#ffdad6',
        'on-surface-variant': '#3c4a41',
        'surface-bright': '#f7faf6',
        'tertiary-fixed-dim': '#deb7ff',
        'inverse-on-surface': '#eef2ee',
        'on-primary-container': '#005033',
        'on-primary-fixed': '#002113',
        'on-error': '#ffffff',
        'secondary': '#835500',
        'surface-dim': '#d8dbd7',
        'tertiary-container': '#d09eff',
        'on-secondary-container': '#6b4500',
        'on-error-container': '#93000a',
        'outline': '#6c7b70',
        'surface-tint': '#006c47',
        'on-tertiary-container': '#631c9f',
        'background': '#FAF5EE',
        'surface-container-lowest': '#ffffff',
        'primary-fixed-dim': '#40e09d',
        'on-secondary-fixed': '#291800',
        'tertiary-fixed': '#f0dbff',
        'inverse-primary': '#40e09d',
        'surface-container-high': '#e6e9e5',
        'on-primary': '#ffffff',
        'on-surface': '#181c1a',
        'secondary-fixed-dim': '#ffb955',
        'outline-variant': '#bbcabf',
        'on-primary-fixed-variant': '#005234',
        'surface-container-highest': '#e0e3df',
        'on-tertiary': '#ffffff',
        'error': '#ba1a1a',
        // Brand accents from the Stitch design system
        'brand-mint': '#1ecc8b',
        'brand-amber': '#f5a623',
        'brand-purple': '#c07eff',
        'brand-cream': '#faf5ee',
        'brand-ink': '#0e1210',
        // Stitch screens reference `accent-*` tokens directly
        'accent-purple': '#c07eff',
        'accent-mint': '#1ecc8b',
        'accent-amber': '#f5a623',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        card: '20px',
        full: '9999px',
      },
      spacing: {
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        base: '4px',
        xs: '8px',
        'card-gap': '16px',
        'container-padding': '20px',
      },
      fontFamily: {
        sans: ['Outfit', 'system-ui', 'sans-serif'],
        'body-lg': ['Outfit'],
        'headline-lg': ['Outfit'],
        'display-lg': ['Outfit'],
        'body-md': ['Outfit'],
        'title-md': ['Outfit'],
        'label-sm': ['Outfit'],
        'label-md': ['Outfit'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
      },
      boxShadow: {
        card: '0 1px 3px rgba(24, 28, 26, 0.06), 0 1px 2px rgba(24, 28, 26, 0.04)',
        'card-lg': '0 8px 24px rgba(24, 28, 26, 0.10)',
        nav: '0 -2px 16px rgba(24, 28, 26, 0.08)',
      },
      keyframes: {
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'pop': {
          '0%': { transform: 'scale(0.8)', opacity: '0' },
          '70%': { transform: 'scale(1.05)' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        shimmer: {
          '100%': { transform: 'translateX(100%)' },
        },
        'slide-in': {
          '0%': { opacity: '0', transform: 'translateX(16px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
      },
      animation: {
        'fade-up': 'fade-up 0.35s ease-out both',
        'pop': 'pop 0.3s cubic-bezier(0.34, 1.56, 0.64, 1) both',
        shimmer: 'shimmer 1.4s infinite',
        'pulse-slow': 'pulse 6s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'slide-in': 'slide-in 0.4s cubic-bezier(0.16, 1, 0.3, 1) both',
      },
    },
  },
  plugins: [],
};
